services:
  database:
    image: postgres:latest
    container_name: database
    env_file:
      - api/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prod_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - api/.env
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - prod_network
    restart: unless-stopped

networks:
  prod_network:
    driver: bridge

volumes:
  postgres_data: