name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./api
        run: npm install

      - name: Run unit tests with coverage
        working-directory: ./api
        run: npm run test:cov

  postman-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file from secrets
        run: |
          cat <<EOF > .env
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          GEOCODING_API_URL=${{ secrets.GEOCODING_API_URL }}
          JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          MAPS_PLATFORM_API_KEY=${{ secrets.MAPS_PLATFORM_API_KEY }}
          PLACES_API_URL=${{ secrets.PLACES_API_URL }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          EOF

      - name: Start Docker services
        run: docker compose up -d

      - name: Wait for API to be ready
        run: |
          echo "Waiting for API to be available at http://localhost:3000..."
          for i in {1..30}; do
            if curl --silent --fail http://localhost:3000/api/v1/healthcheck; then
              echo "API is up!"
              break
            fi
            echo "Still waiting..."
            sleep 5
          done

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection tests
        run: |
          for collection in ./api/collections/*.json; do
            echo "Running collection: $collection"
            newman run "$collection"
          done

      - name: Tear down Docker
        if: always()
        run: docker compose down
